import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Building2, Landmark, Plus, Star, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { apiDelete, apiGet, apiPost, apiPut } from "@/lib/api";
import { formatINR, friendlyError } from "@/lib/format";
import type { Account } from "@/lib/types";

export default function Accounts() {
  const qc = useQueryClient();
  const [showForm, setShowForm] = useState(false);
  const [name, setName] = useState(""); const [type, setType] = useState<"SAVINGS" | "CURRENT">("SAVINGS"); const [balance, setBalance] = useState("");
  const query = useQuery({ queryKey: ["accounts"], queryFn: () => apiGet<Account[]>("/accounts"), retry: false });
  const create = useMutation({ mutationFn: () => apiPost<Account>("/accounts", { name, type, balance: Number(balance), is_default: false }), onSuccess: () => { qc.invalidateQueries({ queryKey: ["accounts"] }); qc.invalidateQueries({ queryKey: ["dashboard"] }); setShowForm(false); setName(""); setBalance(""); toast.success("Account added"); }, onError: (error) => toast.error(friendlyError(error)) });
  const update = useMutation({ mutationFn: ({ account, name: nextName, makeDefault = false }: { account: Account; name?: string; makeDefault?: boolean }) => apiPut<Account>(`/accounts/${account.id}`, { name: nextName ?? account.name, type: account.type, is_default: makeDefault || account.is_default }), onSuccess: () => { qc.invalidateQueries({ queryKey: ["accounts"] }); toast.success("Account updated"); }, onError: (error) => toast.error(friendlyError(error)) });
  const remove = useMutation({ mutationFn: (id: string) => apiDelete<void>(`/accounts/${id}`), onSuccess: () => { qc.invalidateQueries({ queryKey: ["accounts"] }); toast.success("Account removed"); }, onError: (error) => toast.error(friendlyError(error)) });
  return <div className="space-y-6"><div className="page-title-row"><div><p className="section-kicker">Connected money</p><h2 className="page-title" data-testid="accounts-heading">Accounts</h2><p className="page-description">Balances update automatically as transactions move through each account.</p></div><Button onClick={() => setShowForm(!showForm)} className="bg-[#00f5a0] text-[#07110c]" data-testid="account-add-button"><Plus size={16}/> Add account</Button></div>
    {showForm && <form className="panel grid gap-4 sm:grid-cols-[1.4fr_1fr_1fr_auto] sm:items-end" onSubmit={(e) => { e.preventDefault(); create.mutate(); }} data-testid="account-create-form"><div className="space-y-2"><Label>Name</Label><Input value={name} onChange={(e) => setName(e.target.value)} placeholder="ICICI Current" required data-testid="account-name-input"/></div><div className="space-y-2"><Label>Type</Label><select className="form-select" value={type} onChange={(e) => setType(e.target.value as "SAVINGS" | "CURRENT")} data-testid="account-type-select"><option value="SAVINGS">Savings</option><option value="CURRENT">Current</option></select></div><div className="space-y-2"><Label>Opening balance</Label><Input type="number" min="0" value={balance} onChange={(e) => setBalance(e.target.value)} required data-testid="account-balance-input"/></div><Button type="submit" disabled={create.isPending} data-testid="account-save-button">Save account</Button></form>}
    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3" data-testid="accounts-grid">{query.isLoading && Array.from({length:3}).map((_,i)=><div key={i} className="h-44 animate-pulse rounded-2xl bg-white/[.04]"/>)}{query.data?.map((account) => <article className="panel group" key={account.id} data-testid={`account-card-${account.id}`}><div className="flex items-start justify-between"><span className="metric-icon metric-icon-mint">{account.type === "SAVINGS" ? <Landmark size={19}/> : <Building2 size={19}/>}</span>{account.is_default ? <span className="status-dot"><Star size={12} fill="currentColor"/> Default</span> : <button onClick={() => { if (confirm("Delete this empty account?")) remove.mutate(account.id); }} className="icon-button opacity-70 sm:opacity-0 sm:group-hover:opacity-100" data-testid={`account-delete-${account.id}`} aria-label={`Delete ${account.name}`}><Trash2 size={16}/></button>}</div><p className="mt-8 text-sm text-slate-400">{account.name}</p><p className="money-value mt-2 text-3xl" data-testid={`account-balance-${account.id}`}>{formatINR(account.balance)}</p><div className="mt-4 flex items-center justify-between"><p className="text-xs uppercase tracking-[.15em] text-slate-600">{account.type}</p><div className="flex gap-3">{!account.is_default&&<button onClick={()=>update.mutate({account,makeDefault:true})} className="text-xs font-semibold text-[#00f5a0]" data-testid={`account-default-${account.id}`}>Make default</button>}<button onClick={()=>{const next=prompt("Account name",account.name);if(next&&next.trim().length>1)update.mutate({account,name:next.trim()});}} className="text-xs text-slate-500 hover:text-slate-200" data-testid={`account-rename-${account.id}`}>Rename</button></div></div></article>)}</section>
    {query.data?.length === 0 && <div className="empty-state" data-testid="accounts-empty-state"><Landmark/><p>No accounts yet. Add your first account to create a financial baseline.</p></div>}
  </div>;
}