import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertCircle, ArrowUp, BrainCircuit, CircleDollarSign, MessageCircle, ShieldCheck, Sparkles, Target, Trash2, TrendingUp } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { apiDelete, apiGet, apiPostStream } from "@/lib/api";
import { formatINR, friendlyError } from "@/lib/format";
import type { CoachExchange, DashboardSummary } from "@/lib/types";

const PROMPTS = [
  "Where can I reduce spending without hurting my essentials?",
  "How healthy is my current savings rate?",
  "Suggest three practical money moves for next month.",
  "How can I reach my top goal faster?",
];

function AnswerText({ text, testId }: { text: string; testId: string }) {
  return <div className="space-y-2 text-sm leading-7 text-slate-300" data-testid={testId}>{text.split("\n").filter(Boolean).map((line, index) => line.trim().startsWith("-") || /^\d+\./.test(line.trim()) ? <p key={`${line}-${index}`} className="flex gap-2"><span className="mt-3 h-1.5 w-1.5 shrink-0 rounded-full bg-[#00f5a0]"/><span>{line.replace(/^[-*]\s*/, "").replace(/^\d+\.\s*/, "")}</span></p> : <p key={`${line}-${index}`}>{line.replaceAll("**", "")}</p>)}</div>;
}

export default function AskWealth() {
  const qc = useQueryClient(); const [question, setQuestion] = useState(""); const [streamed, setStreamed] = useState("");
  const history = useQuery({ queryKey: ["coach-history"], queryFn: () => apiGet<CoachExchange[]>("/coach/history"), retry: false });
  const dashboard = useQuery({ queryKey: ["dashboard"], queryFn: () => apiGet<DashboardSummary>("/dashboard"), retry: false });
  const ask = useMutation({
    mutationFn: (message: string) => apiPostStream<CoachExchange>("/coach/message", { message }, (event) => { if (event.type === "token") setStreamed((current) => current + event.content); }),
    onMutate: () => setStreamed(""),
    onSuccess: (exchange) => { qc.setQueryData<CoachExchange[]>(["coach-history"], (current) => [...(current ?? []), exchange]); setStreamed(""); },
    onError: (error) => { setStreamed(""); toast.error(friendlyError(error)); },
  });
  const clear = useMutation({ mutationFn: () => apiDelete<void>("/coach/history"), onSuccess: () => { qc.setQueryData(["coach-history"], []); toast.success("Conversation history cleared"); }, onError: (error) => toast.error(friendlyError(error)) });
  function submit(message = question) { const next = message.trim(); if (next.length < 3 || ask.isPending) return; setQuestion(""); ask.mutate(next); }
  const data = dashboard.data;

  return <div className="space-y-6"><div className="page-title-row"><div><p className="section-kicker"><Sparkles size={13}/> Gemini financial coach</p><h2 className="page-title" data-testid="ask-wealth-heading">Ask Wealth</h2><p className="page-description" data-testid="ask-wealth-description">Personalized answers and suggestions grounded in your real financial aggregates.</p></div><div className="flex items-center gap-2"><span className="status-dot" data-testid="coach-read-only-status"><ShieldCheck size={12}/> Read-only guidance</span>{(history.data?.length??0)>0&&<button onClick={()=>{if(confirm("Clear your private conversation history?"))clear.mutate();}} className="icon-button" data-testid="coach-clear-history-button" aria-label="Clear conversation history"><Trash2 size={16}/></button>}</div></div>
    <section className="grid gap-6 xl:grid-cols-[1fr_320px]">
      <div className="flex min-h-[650px] flex-col overflow-hidden rounded-2xl border border-white/8 bg-[#0c111b] shadow-2xl" data-testid="coach-chat-panel">
        <div className="flex items-center justify-between border-b border-white/8 px-5 py-4"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#00f5a0]/10 text-[#00f5a0]"><BrainCircuit size={19}/></span><div><p className="text-sm font-semibold">Wealth Coach</p><p className="text-[10px] uppercase tracking-[.15em] text-slate-600">Grounded in your data</p></div></div><span className="flex items-center gap-2 text-xs text-slate-500"><span className="h-2 w-2 rounded-full bg-[#00f5a0] shadow-[0_0_9px_#00f5a0]"/> Gemini online</span></div>
        <div className="flex-1 space-y-7 overflow-y-auto p-5 sm:p-7" data-testid="coach-conversation">
          {!history.isLoading && history.data?.length===0 && !ask.isPending && <div className="mx-auto max-w-xl py-12 text-center" data-testid="coach-empty-state"><span className="mx-auto grid h-14 w-14 place-items-center rounded-2xl border border-[#00f5a0]/20 bg-[#00f5a0]/[.06] text-[#00f5a0]"><MessageCircle size={25}/></span><h3 className="mt-6 font-heading text-2xl font-semibold">What should we work through?</h3><p className="mt-3 text-sm leading-6 text-slate-500">Ask about spending patterns, budget pressure, savings health, or the next best move for a goal.</p><div className="mt-7 grid gap-2 sm:grid-cols-2">{PROMPTS.map((prompt,index)=><button key={prompt} onClick={()=>submit(prompt)} className="rounded-xl border border-white/8 bg-white/[.02] p-3 text-left text-xs leading-5 text-slate-400 transition-[border-color,color,transform] hover:-translate-y-0.5 hover:border-[#00f5a0]/25 hover:text-slate-200" data-testid={`coach-starter-prompt-${index}`}>{prompt}</button>)}</div></div>}
          {history.data?.map((exchange,index)=><article key={exchange.id} className="space-y-3" data-testid={`coach-exchange-${exchange.id}`}><div className="ml-auto max-w-[85%] rounded-2xl rounded-br-md bg-[#00f5a0] px-4 py-3 text-sm font-medium text-[#07110c]" data-testid={`coach-question-${index}`}>{exchange.question}</div><div className="max-w-[92%] rounded-2xl rounded-bl-md border border-white/8 bg-white/[.03] p-5" data-testid={`coach-answer-${index}`}><div className="mb-4 flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[.16em] text-cyan-300"><Sparkles size={13}/> Personalized guidance</div><AnswerText text={exchange.answer} testId={`coach-answer-text-${index}`}/><p className="mt-4 text-[10px] text-slate-600">{new Date(exchange.created_at).toLocaleString("en-IN")}</p></div></article>)}
          {ask.isPending&&<article className="space-y-3" data-testid="coach-streaming-response"><div className="ml-auto max-w-[85%] rounded-2xl rounded-br-md bg-[#00f5a0]/80 px-4 py-3 text-sm font-medium text-[#07110c]">{ask.variables}</div><div className="max-w-[92%] rounded-2xl rounded-bl-md border border-cyan-400/15 bg-cyan-400/[.025] p-5"><div className="mb-4 flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[.16em] text-cyan-300"><Sparkles size={13}/> Thinking with your data <span className="inline-block h-1.5 w-1.5 animate-pulse rounded-full bg-cyan-300"/></div>{streamed?<AnswerText text={streamed} testId="coach-streamed-answer"/>:<p className="text-sm text-slate-500">Reviewing your financial baseline…</p>}</div></article>}
        </div>
        <div className="border-t border-white/8 bg-[#090d15] p-4"><div className="rounded-2xl border border-white/10 bg-[#0f1420] p-2 focus-within:border-[#00f5a0]/25"><textarea value={question} onChange={(event)=>setQuestion(event.target.value)} onKeyDown={(event)=>{if(event.key==="Enter"&&!event.shiftKey){event.preventDefault();submit();}}} placeholder="Ask about your spending, savings, budget, or goals…" className="min-h-20 w-full resize-none bg-transparent px-3 py-2 text-sm text-slate-100 outline-none placeholder:text-slate-600" maxLength={500} data-testid="coach-question-input"/><div className="flex items-center justify-between px-2 pb-1"><span className="text-[10px] text-slate-600" data-testid="coach-character-count">{question.length}/500 · Enter to send</span><Button size="icon" onClick={()=>submit()} disabled={ask.isPending||question.trim().length<3} className="rounded-xl bg-[#00f5a0] text-[#07110c] hover:bg-[#3fffb8]" data-testid="coach-send-button" aria-label="Send question"><ArrowUp size={17}/></Button></div></div></div>
      </div>
      <aside className="space-y-4"><article className="panel" data-testid="coach-context-card"><p className="metric-label">Context available to AI</p><p className="mt-3 text-sm leading-6 text-slate-400">Only these aggregates are shared—never raw transactions or receipt images.</p><div className="mt-6 space-y-4">{data&&<><div className="flex items-center justify-between"><span className="flex items-center gap-2 text-xs text-slate-500"><CircleDollarSign size={14}/>Monthly savings</span><span className="money-value text-sm" data-testid="coach-context-savings">{formatINR(data.net_cash_flow/Math.max(data.monthly_flow.length,1))}</span></div><div className="flex items-center justify-between"><span className="flex items-center gap-2 text-xs text-slate-500"><TrendingUp size={14}/>Savings rate</span><span className="money-value text-sm" data-testid="coach-context-rate">{data.savings_rate}%</span></div><div className="flex items-center justify-between"><span className="flex items-center gap-2 text-xs text-slate-500"><Target size={14}/>Active goals</span><span className="money-value text-sm" data-testid="coach-context-goals">{data.goals.length}</span></div></>}</div></article><article className="rounded-2xl border border-amber-400/15 bg-amber-400/[.035] p-5" data-testid="coach-safety-card"><AlertCircle size={18} className="text-amber-300"/><h3 className="mt-4 font-heading font-semibold">Guidance, not execution</h3><p className="mt-2 text-sm leading-6 text-slate-500">Ask Wealth can suggest next steps but cannot create transactions, change budgets, or move money.</p></article><article className="panel"><p className="metric-label">Try a focused question</p><div className="mt-4 space-y-2">{PROMPTS.slice(0,3).map((prompt,index)=><button key={prompt} onClick={()=>setQuestion(prompt)} className="flex w-full items-start gap-2 rounded-lg p-2 text-left text-xs leading-5 text-slate-500 transition-[background-color,color] hover:bg-white/[.04] hover:text-slate-200" data-testid={`coach-side-prompt-${index}`}><span className="mt-2 h-1 w-1 shrink-0 rounded-full bg-[#00f5a0]"/>{prompt}</button>)}</div></article></aside>
    </section>
    <p className="disclaimer" data-testid="coach-disclaimer">Ask Wealth provides educational decision support based on recorded aggregates. It is not a financial adviser, and actual outcomes may differ.</p>
  </div>;
}