import { useQuery } from "@tanstack/react-query";
import { useNavigate } from "react-router-dom";
import { ArrowDownRight, ArrowRight, ArrowUpRight, CircleDollarSign, MessageCircle, Sparkles, Target, TrendingUp, Wallet } from "lucide-react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Button } from "@/components/ui/button";
import { apiGet } from "@/lib/api";
import { formatINR } from "@/lib/format";
import type { DashboardSummary } from "@/lib/types";

const fetchDashboard = () => apiGet<DashboardSummary>("/dashboard");

function MetricCard({ label, value, icon: Icon, tone = "mint", testId }: { label: string; value: string; icon: typeof Wallet; tone?: "mint" | "cyan" | "amber"; testId: string }) {
  return <article className="metric-card" data-testid={testId}><div className={`metric-icon metric-icon-${tone}`}><Icon size={18} /></div><p className="metric-label">{label}</p><p className="money-value mt-3 text-2xl">{value}</p></article>;
}

export default function Dashboard() {
  const navigate = useNavigate();
  const { data, isLoading, isError } = useQuery({ queryKey: ["dashboard"], queryFn: fetchDashboard, retry: false });
  return <div className="space-y-6">
    <section className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="section-kicker" data-testid="dashboard-kicker">Financial control room</p><h2 className="mt-3 font-heading text-3xl font-bold tracking-tight sm:text-4xl" data-testid="dashboard-heading">Your money, translated into decisions.</h2><p className="mt-2 text-sm text-slate-400" data-testid="dashboard-description">Live analytics across accounts, cash flow, goals and monthly limits.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => navigate("/ask")} className="border-cyan-400/20 bg-cyan-400/[.04] text-cyan-200" data-testid="dashboard-ask-wealth-button"><MessageCircle size={16}/> Ask Wealth</Button><Button variant="outline" onClick={() => navigate("/what-if")} className="border-[#00f5a0]/25 bg-[#00f5a0]/5 text-[#00f5a0]" data-testid="dashboard-open-simulator-button"><Sparkles size={16} /> Ask a What-If</Button></div></section>
    {isLoading && <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5" data-testid="dashboard-loading-state">{Array.from({ length: 5 }).map((_, i) => <div key={i} className="h-36 animate-pulse rounded-2xl bg-white/[.04]" />)}</div>}
    {isError && <div className="error-panel" data-testid="dashboard-error-state">Your financial data is temporarily unavailable. The rest of Wealth is still ready.</div>}
    {data && <>
      <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5" data-testid="dashboard-metrics-grid"><MetricCard label="Total balance" value={formatINR(data.total_balance, true)} icon={Wallet} testId="net-worth-value-display" /><MetricCard label="Total income" value={formatINR(data.total_income, true)} icon={ArrowUpRight} tone="cyan" testId="dashboard-total-income" /><MetricCard label="Total expenses" value={formatINR(data.total_expenses, true)} icon={ArrowDownRight} tone="amber" testId="dashboard-total-expenses" /><MetricCard label="Net cash flow" value={formatINR(data.net_cash_flow, true)} icon={TrendingUp} testId="dashboard-net-cash-flow" /><MetricCard label="Budget remaining" value={formatINR(data.budget_remaining, true)} icon={CircleDollarSign} tone="cyan" testId="dashboard-budget-remaining" /></section>
      <section className="grid gap-6 xl:grid-cols-[1.5fr_.8fr]">
        <article className="panel" data-testid="dashboard-cash-flow-panel"><div className="panel-header"><div><p className="metric-label">Cash flow</p><h3 className="mt-2 font-heading text-xl font-semibold">Income vs expenses</h3></div><span className={`status-dot ${data.savings_rate < 0 ? "!text-rose-300" : ""}`} data-testid="dashboard-savings-rate">{data.savings_rate}% savings rate</span></div><div className="mt-8 h-72" data-testid="dashboard-cash-flow-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data.monthly_flow}><defs><linearGradient id="income" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#00f5a0" stopOpacity={.28}/><stop offset="1" stopColor="#00f5a0" stopOpacity={0}/></linearGradient><linearGradient id="expense" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#00e5ff" stopOpacity={.18}/><stop offset="1" stopColor="#00e5ff" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="rgba(255,255,255,.06)" vertical={false}/><XAxis dataKey="month" tick={{ fill: "#64748b", fontSize: 11 }} axisLine={false} tickLine={false}/><YAxis tick={{ fill: "#64748b", fontSize: 11 }} axisLine={false} tickLine={false} tickFormatter={(v: number) => `₹${Math.round(v / 1000)}k`}/><Tooltip contentStyle={{ background: "#111827", border: "1px solid rgba(255,255,255,.1)", borderRadius: 12 }} formatter={(value: number) => formatINR(value)}/><Area type="monotone" dataKey="income" stroke="#00f5a0" fill="url(#income)" strokeWidth={2.5}/><Area type="monotone" dataKey="expenses" stroke="#00e5ff" fill="url(#expense)" strokeWidth={2.5}/></AreaChart></ResponsiveContainer></div></article>
        <article className="whatif-card" data-testid="dashboard-what-if-preview"><div className="absolute right-0 top-0 h-40 w-40 rounded-full bg-[#00f5a0]/10 blur-3xl"/><div className="relative"><div className="flex items-center gap-2 text-[#00f5a0]"><Sparkles size={17}/><span className="text-xs font-semibold uppercase tracking-[.18em]">Decision lab</span></div><h3 className="mt-6 font-heading text-2xl font-semibold leading-snug">What happens if you save ₹3,000 more every month?</h3><p className="mt-4 text-sm leading-6 text-slate-400">Use your actual cash-flow baseline to see the 12-month impact and how much sooner you could fund your top goal.</p><button onClick={() => navigate("/what-if", { state: { prompt: "What if I save ₹3,000 more every month?" } })} className="mt-8 flex w-full items-center justify-between rounded-xl bg-[#00f5a0] px-4 py-3 text-sm font-bold text-[#07110c] transition-[transform,background-color] duration-200 hover:-translate-y-0.5 hover:bg-[#3fffb8]" data-testid="dashboard-simulate-button">Run this simulation <ArrowRight size={17}/></button></div></article>
      </section>
      <section className="grid gap-6 xl:grid-cols-2"><article className="panel" data-testid="dashboard-recent-transactions"><div className="panel-header"><h3 className="font-heading text-xl font-semibold">Recent activity</h3><button onClick={() => navigate("/transactions")} className="text-xs font-semibold text-[#00f5a0]" data-testid="dashboard-view-transactions">View all</button></div><div className="mt-4 divide-y divide-white/6">{data.recent_transactions.map((item) => <div key={item.id} className="flex items-center justify-between py-3" data-testid={`dashboard-transaction-${item.id}`}><div><p className="text-sm font-medium">{item.description}</p><p className="mt-1 text-xs text-slate-500">{item.category} · {item.date}</p></div><p className={`money-value text-sm ${item.type === "INCOME" ? "text-[#00f5a0]" : "text-slate-200"}`}>{item.type === "EXPENSE" ? "−" : "+"}{formatINR(item.amount)}</p></div>)}</div></article><article className="panel" data-testid="dashboard-goals"><div className="panel-header"><h3 className="font-heading text-xl font-semibold">Goals in motion</h3><button onClick={() => navigate("/goals")} className="text-xs font-semibold text-[#00f5a0]" data-testid="dashboard-view-goals">Manage</button></div><div className="mt-5 space-y-5">{data.goals.length ? data.goals.slice(0, 3).map((goal) => <div key={goal.id} data-testid={`dashboard-goal-${goal.id}`}><div className="mb-2 flex items-center justify-between"><span className="flex items-center gap-2 text-sm font-medium"><Target size={15} className="text-cyan-300" />{goal.name}</span><span className="money-value text-xs">{formatINR(goal.current_amount)} / {formatINR(goal.target_amount)}</span></div><div className="progress-track"><div className="progress-fill" style={{ width: `${goal.progress_percentage}%` }}/></div><p className="mt-2 text-xs text-slate-500">{goal.progress_percentage}% funded · projected {goal.projected_completion ?? "after positive cash flow"}</p></div>) : <p className="empty-copy">Create a goal to unlock goal-aware simulations.</p>}</div></article></section>
    </>}
  </div>;
}