import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Flag, Plus, Target, Trash2, TrendingUp } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { apiDelete, apiGet, apiPost } from "@/lib/api";
import { formatINR, friendlyError } from "@/lib/format";
import type { Goal } from "@/lib/types";

export default function Goals() {
  const qc=useQueryClient(); const [show,setShow]=useState(false); const [contributing,setContributing]=useState<string|null>(null); const [contribution,setContribution]=useState("");
  const [form,setForm]=useState({name:"",target_amount:"",current_amount:"0",target_date:"",priority:"2",category:"Savings"});
  const query=useQuery({queryKey:["goals"],queryFn:()=>apiGet<Goal[]>("/goals"),retry:false});
  const create=useMutation({mutationFn:()=>apiPost<Goal>("/goals",{...form,target_amount:Number(form.target_amount),current_amount:Number(form.current_amount),priority:Number(form.priority),target_date:form.target_date||null}),onSuccess:()=>{qc.invalidateQueries({queryKey:["goals"]});qc.invalidateQueries({queryKey:["dashboard"]});setShow(false);setForm({...form,name:"",target_amount:""});toast.success("Goal created");},onError:(error)=>toast.error(friendlyError(error))});
  const contribute=useMutation({mutationFn:(id:string)=>apiPost<Goal>(`/goals/${id}/contribute`,{amount:Number(contribution)}),onSuccess:()=>{qc.invalidateQueries({queryKey:["goals"]});qc.invalidateQueries({queryKey:["dashboard"]});setContributing(null);setContribution("");toast.success("Contribution added");},onError:(error)=>toast.error(friendlyError(error))});
  const remove=useMutation({mutationFn:(id:string)=>apiDelete<void>(`/goals/${id}`),onSuccess:()=>{qc.invalidateQueries({queryKey:["goals"]});toast.success("Goal removed");},onError:(error)=>toast.error(friendlyError(error))});
  const update=(key:string,value:string)=>setForm((current)=>({...current,[key]:value}));
  return <div className="space-y-6"><div className="page-title-row"><div><p className="section-kicker">Purpose-led saving</p><h2 className="page-title" data-testid="goals-heading">Financial goals</h2><p className="page-description">Give every scenario a destination worth accelerating.</p></div><Button onClick={()=>setShow(!show)} className="bg-[#00f5a0] text-[#07110c]" data-testid="goal-add-button"><Plus size={16}/> New goal</Button></div>
    {show&&<form className="panel grid gap-4 sm:grid-cols-2 xl:grid-cols-6 xl:items-end" onSubmit={(e)=>{e.preventDefault();create.mutate();}} data-testid="goal-create-form"><div className="space-y-2 xl:col-span-2"><Label>Goal name</Label><Input value={form.name} onChange={(e)=>update("name",e.target.value)} placeholder="Emergency Fund" required data-testid="goal-name-input"/></div><div className="space-y-2"><Label>Target (₹)</Label><Input type="number" min="1" value={form.target_amount} onChange={(e)=>update("target_amount",e.target.value)} required data-testid="goal-target-input"/></div><div className="space-y-2"><Label>Already saved</Label><Input type="number" min="0" value={form.current_amount} onChange={(e)=>update("current_amount",e.target.value)} data-testid="goal-current-input"/></div><div className="space-y-2"><Label>Target date</Label><Input type="date" value={form.target_date} onChange={(e)=>update("target_date",e.target.value)} data-testid="goal-date-input"/></div><Button type="submit" disabled={create.isPending} data-testid="goal-save-button">Create goal</Button></form>}
    <section className="grid gap-5 md:grid-cols-2 xl:grid-cols-3" data-testid="goals-grid">{query.data?.map((goal,index)=><article className="panel group" key={goal.id} data-testid={index===0?"goal-card-home-downpayment":`goal-card-${goal.id}`}><div className="flex items-start justify-between"><span className="metric-icon metric-icon-cyan"><Target size={19}/></span><div className="flex gap-1"><span className="status-dot">P{goal.priority}</span><button onClick={()=>{if(confirm("Delete this goal?"))remove.mutate(goal.id);}} className="icon-button opacity-70 sm:opacity-0 sm:group-hover:opacity-100" data-testid={`goal-delete-${goal.id}`} aria-label={`Delete ${goal.name}`}><Trash2 size={15}/></button></div></div><h3 className="mt-7 font-heading text-xl font-semibold">{goal.name}</h3><p className="mt-1 text-xs text-slate-500">{goal.category}</p><div className="mt-6 flex items-end justify-between"><div><p className="metric-label">Saved</p><p className="money-value mt-1 text-lg">{formatINR(goal.current_amount)}</p></div><p className="money-value text-sm text-slate-400">of {formatINR(goal.target_amount)}</p></div><div className="progress-track mt-4"><div className="progress-fill" style={{width:`${goal.progress_percentage}%`}}/></div><div className="mt-3 flex justify-between text-xs text-slate-500"><span>{goal.progress_percentage}% funded</span><span>{formatINR(goal.remaining_amount)} left</span></div><div className="mt-6 flex items-center justify-between rounded-xl bg-white/[.035] p-3"><span className="flex items-center gap-2 text-xs text-slate-400"><TrendingUp size={14} className="text-[#00f5a0]"/>Projected</span><span className="text-xs font-semibold">{goal.projected_completion??"Needs positive cash flow"}</span></div>{contributing===goal.id?<div className="mt-4 flex gap-2"><Input type="number" min="1" value={contribution} onChange={(e)=>setContribution(e.target.value)} placeholder="Contribution ₹" data-testid={`goal-contribution-input-${goal.id}`}/><Button onClick={()=>contribute.mutate(goal.id)} disabled={!contribution} data-testid={`goal-contribution-save-${goal.id}`}>Add</Button></div>:<Button variant="outline" className="mt-4 w-full border-white/10" onClick={()=>setContributing(goal.id)} data-testid={`goal-contribute-${goal.id}`}>Add contribution</Button>}</article>)}</section>
    {query.data?.length===0&&<div className="empty-state" data-testid="goals-empty-state"><Flag/><h3>No financial goals yet</h3><p>Create your first goal to unlock goal-impact simulations.</p></div>}
  </div>;
}