import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useNavigate } from "react-router-dom";
import { AlertTriangle, ArrowRight, CheckCircle2, FileImage, ScanLine, ShieldCheck, Sparkles, UploadCloud, X } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { apiGet, apiPost, apiUpload } from "@/lib/api";
import { formatINR, friendlyError } from "@/lib/format";
import type { Account, ReceiptExtraction, ReceiptScanResponse, Transaction, TransactionInput } from "@/lib/types";

const CATEGORIES = ["Food", "Groceries", "Dining", "Shopping", "Transport", "Fuel", "Rent", "Utilities", "Bills", "Healthcare", "Education", "Entertainment", "Travel", "UPI", "Subscription", "Other"];

export default function ReceiptScanner() {
  const navigate = useNavigate(); const qc = useQueryClient();
  const [file, setFile] = useState<File | null>(null); const [preview, setPreview] = useState<string | null>(null);
  const [draft, setDraft] = useState<ReceiptExtraction | null>(null); const [warnings, setWarnings] = useState<string[]>([]); const [accountId, setAccountId] = useState("");
  const accounts = useQuery({ queryKey: ["accounts"], queryFn: () => apiGet<Account[]>("/accounts"), retry: false });
  const scan = useMutation({ mutationFn: () => { if (!file) throw new Error("No file"); return apiUpload<ReceiptScanResponse>("/receipts/scan", file); }, onSuccess: (data) => { setDraft(data.extraction); setWarnings(data.warnings); setAccountId(accounts.data?.find((item) => item.is_default)?.id ?? accounts.data?.[0]?.id ?? ""); toast.success("Gemini extracted the receipt. Review every field before saving."); }, onError: (error) => toast.error(friendlyError(error)) });
  const save = useMutation({ mutationFn: () => { if (!draft) throw new Error("No draft"); const payload: TransactionInput = { ...draft, date: draft.date ?? "", merchant: draft.merchant || null, account_id: accountId, is_recurring: false, recurring_interval: null }; return apiPost<Transaction>("/transactions", payload); }, onSuccess: () => { ["transactions", "accounts", "dashboard", "budget"].forEach((key) => qc.invalidateQueries({ queryKey: [key] })); toast.success("Transaction confirmed and saved"); navigate("/transactions"); }, onError: (error) => toast.error(friendlyError(error)) });

  function choose(next: File | undefined) {
    if (!next) return;
    if (!["image/jpeg", "image/png", "image/webp"].includes(next.type)) { toast.error("Choose a JPG, PNG, or WEBP image"); return; }
    if (next.size > 8 * 1024 * 1024) { toast.error("Image must be 8 MB or smaller"); return; }
    setFile(next); setDraft(null); setWarnings([]); setPreview(URL.createObjectURL(next));
  }
  function change<K extends keyof ReceiptExtraction>(key: K, value: ReceiptExtraction[K]) { setDraft((current) => current ? { ...current, [key]: value } : current); }
  function reset() { setFile(null); setPreview(null); setDraft(null); setWarnings([]); }

  return <div className="space-y-6"><div className="page-title-row"><div><p className="section-kicker"><Sparkles size={13}/> Gemini vision</p><h2 className="page-title" data-testid="receipt-scanner-heading">Receipt & bill scanner</h2><p className="page-description" data-testid="receipt-scanner-description">Extract the details, review them, then decide what gets saved.</p></div><span className="status-dot" data-testid="receipt-privacy-status"><ShieldCheck size={12}/> Images aren’t stored</span></div>
    {!draft ? <section className="grid gap-6 lg:grid-cols-[1.15fr_.85fr]">
      <article className="panel" data-testid="receipt-upload-panel"><label onDragOver={(event)=>event.preventDefault()} onDrop={(event)=>{event.preventDefault();choose(event.dataTransfer.files[0]);}} className={`flex min-h-[360px] cursor-pointer flex-col items-center justify-center rounded-2xl border border-dashed p-8 text-center transition-[border-color,background-color] ${file?"border-[#00f5a0]/30 bg-[#00f5a0]/[.035]":"border-white/15 bg-white/[.015] hover:border-[#00f5a0]/30"}`} data-testid="receipt-dropzone"><input type="file" accept="image/jpeg,image/png,image/webp" className="sr-only" onChange={(event)=>choose(event.target.files?.[0])} data-testid="receipt-file-input"/>{preview?<img src={preview} alt="Selected receipt preview" className="max-h-64 max-w-full rounded-xl object-contain shadow-2xl" data-testid="receipt-image-preview"/>:<><span className="grid h-14 w-14 place-items-center rounded-2xl bg-[#00f5a0]/10 text-[#00f5a0]"><UploadCloud size={26}/></span><h3 className="mt-6 font-heading text-xl font-semibold">Drop a receipt or bill here</h3><p className="mt-2 max-w-sm text-sm leading-6 text-slate-500">Or tap to choose a clear, well-lit JPG, PNG, or WEBP image up to 8 MB.</p></>}</label>{file&&<div className="mt-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex min-w-0 items-center gap-3"><FileImage size={18} className="shrink-0 text-cyan-300"/><div className="min-w-0"><p className="truncate text-sm font-medium" data-testid="receipt-file-name">{file.name}</p><p className="text-xs text-slate-500" data-testid="receipt-file-size">{(file.size/1024/1024).toFixed(2)} MB</p></div></div><div className="flex gap-2"><Button variant="ghost" onClick={reset} data-testid="receipt-remove-button"><X size={15}/> Remove</Button><Button onClick={()=>scan.mutate()} disabled={scan.isPending} className="bg-[#00f5a0] text-[#07110c]" data-testid="receipt-scan-button">{scan.isPending?"Gemini is reading…":"Scan with Gemini"}<ScanLine size={16}/></Button></div></div>}</article>
      <aside className="space-y-4"><article className="panel"><p className="metric-label">Safe confirmation flow</p><div className="mt-6 space-y-5">{["Gemini reads only this image","Structured fields are schema-validated","You edit anything uncertain","Nothing is saved until you confirm"].map((text,index)=><div className="flex gap-3" key={text} data-testid={`receipt-flow-step-${index}`}><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full border border-[#00f5a0]/20 bg-[#00f5a0]/5 font-mono text-xs text-[#00f5a0]">{index+1}</span><p className="pt-1 text-sm text-slate-300">{text}</p></div>)}</div></article><article className="rounded-2xl border border-amber-400/15 bg-amber-400/[.035] p-5" data-testid="receipt-capture-tip"><AlertTriangle className="text-amber-300" size={19}/><h3 className="mt-4 font-heading font-semibold">For the best read</h3><p className="mt-2 text-sm leading-6 text-slate-500">Keep the full receipt in frame, avoid glare, and make the total and date easy to see.</p></article></aside>
    </section> : <section className="grid gap-6 xl:grid-cols-[.7fr_1.3fr]" data-testid="receipt-review-section">
      <article className="panel h-fit"><div className="panel-header"><div><p className="metric-label">Original image</p><h3 className="mt-2 font-heading text-lg font-semibold">Visual reference</h3></div><button onClick={reset} className="icon-button" data-testid="receipt-review-reset-button" aria-label="Scan another receipt"><X size={17}/></button></div>{preview&&<img src={preview} alt="Receipt being reviewed" className="mt-5 max-h-[520px] w-full rounded-xl bg-black/20 object-contain" data-testid="receipt-review-image"/>}</article>
      <article className="panel"><div className="panel-header"><div><p className="metric-label">AI extraction · editable</p><h3 className="mt-2 font-heading text-2xl font-semibold" data-testid="receipt-review-heading">Review before saving</h3></div><span className="status-dot"><CheckCircle2 size={12}/> Schema valid</span></div>{warnings.length>0&&<div className="mt-5 rounded-xl border border-amber-400/15 bg-amber-400/[.04] p-4" data-testid="receipt-warnings"><p className="text-xs font-semibold text-amber-200">Needs your attention</p>{warnings.map((warning,index)=><p key={warning} className="mt-2 text-xs leading-5 text-slate-400" data-testid={`receipt-warning-${index}`}>• {warning}</p>)}</div>}
        <div className="mt-6 grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label>Transaction type</Label><select className="form-select" value={draft.type} onChange={(e)=>change("type",e.target.value as ReceiptExtraction["type"])} data-testid="receipt-type-select"><option value="EXPENSE">Expense</option><option value="INCOME">Income</option></select></div><div className="space-y-2"><Label>Amount (₹)</Label><Input type="number" min="0.01" step="0.01" value={draft.amount} onChange={(e)=>change("amount",Number(e.target.value))} data-testid="receipt-amount-input"/></div><div className="space-y-2"><Label>Merchant</Label><Input value={draft.merchant??""} onChange={(e)=>change("merchant",e.target.value||null)} placeholder="Merchant name" data-testid="receipt-merchant-input"/></div><div className="space-y-2"><Label>Date</Label><Input type="date" value={draft.date??""} onChange={(e)=>change("date",e.target.value||null)} required data-testid="receipt-date-input"/></div><div className="space-y-2"><Label>Category</Label><select className="form-select" value={draft.category} onChange={(e)=>change("category",e.target.value)} data-testid="receipt-category-select">{CATEGORIES.map((category)=><option key={category} value={category} label={category}/>)}</select></div><div className="space-y-2"><Label>Account</Label><select className="form-select" value={accountId} onChange={(e)=>setAccountId(e.target.value)} required data-testid="receipt-account-select">{accounts.data?.map((account)=><option key={account.id} value={account.id} label={`${account.name} · ${formatINR(account.balance)}`}/>)}</select></div><div className="space-y-2 sm:col-span-2"><Label>Description</Label><Input value={draft.description} onChange={(e)=>change("description",e.target.value)} data-testid="receipt-description-input"/></div></div>
        <div className="mt-7 flex flex-col-reverse gap-3 border-t border-white/8 pt-5 sm:flex-row sm:items-center sm:justify-between"><p className="flex items-center gap-2 text-xs text-slate-500"><ShieldCheck size={14} className="text-[#00f5a0]"/>Saving will update the selected account balance.</p><Button onClick={()=>save.mutate()} disabled={save.isPending||!draft.date||!accountId||draft.amount<=0||draft.description.trim().length<2} className="bg-[#00f5a0] text-[#07110c]" data-testid="receipt-confirm-save-button">{save.isPending?"Saving transaction…":"Confirm & save transaction"}<ArrowRight size={16}/></Button></div>
      </article>
    </section>}
    <p className="disclaimer" data-testid="receipt-disclaimer">AI extraction can make mistakes. Always verify the amount, date, merchant, category, and account before confirmation.</p>
  </div>;
}