import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useNavigate, useSearchParams } from "react-router-dom";
import { ArrowDownLeft, ArrowUpRight, Pencil, Plus, ScanLine, Search, Trash2, X } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { apiDelete, apiGet, apiPost, apiPut } from "@/lib/api";
import { formatINR, friendlyError } from "@/lib/format";
import type { Account, Transaction, TransactionInput, TransactionList } from "@/lib/types";

const EXPENSE_CATEGORIES = ["Food", "Groceries", "Dining", "Shopping", "Transport", "Fuel", "Rent", "Utilities", "Bills", "Healthcare", "Education", "Entertainment", "Travel", "UPI", "Subscription", "Other"];
const INCOME_CATEGORIES = ["Salary", "Freelance", "Business", "Investment", "Gift", "Other"];

export default function Transactions() {
  const qc = useQueryClient(); const [params, setParams] = useSearchParams(); const navigate = useNavigate();
  const [search, setSearch] = useState(""); const [filter, setFilter] = useState(""); const [sort, setSort] = useState("newest"); const [selected, setSelected] = useState<string[]>([]); const [editingId, setEditingId] = useState<string | null>(null);
  const [form, setForm] = useState({ type: "EXPENSE" as "INCOME" | "EXPENSE", amount: "", description: "", merchant: "", category: "Food", date: new Date().toISOString().slice(0,10), account_id: "", is_recurring: false, recurring_interval: "MONTHLY" });
  const showForm = params.get("new") === "1";
  const queryString = useMemo(() => new URLSearchParams({ ...(search && { search }), ...(filter && { transaction_type: filter }), sort }).toString(), [search, filter, sort]);
  const list = useQuery({ queryKey: ["transactions", search, filter, sort], queryFn: () => apiGet<TransactionList>(`/transactions?${queryString}`), retry: false });
  const accounts = useQuery({ queryKey: ["accounts"], queryFn: () => apiGet<Account[]>("/accounts"), retry: false });
  const create = useMutation({ mutationFn: () => { const accountId = form.account_id || accounts.data?.[0]?.id || ""; const payload: TransactionInput = { ...form, amount: Number(form.amount), merchant: form.merchant || null, account_id: accountId, recurring_interval: form.is_recurring ? form.recurring_interval as TransactionInput["recurring_interval"] : null }; return editingId ? apiPut<Transaction>(`/transactions/${editingId}`, payload) : apiPost<Transaction>("/transactions", payload); }, onSuccess: () => { ["transactions", "accounts", "dashboard", "budget"].forEach((key) => qc.invalidateQueries({ queryKey: [key] })); setParams({}); setEditingId(null); setForm((v) => ({...v, amount:"", description:"", merchant:""})); toast.success(editingId ? "Transaction updated and balance recalculated" : "Transaction saved and balance updated"); }, onError: (error) => toast.error(friendlyError(error)) });
  const remove = useMutation({ mutationFn: (id: string) => apiDelete<void>(`/transactions/${id}`), onSuccess: () => { qc.invalidateQueries({ queryKey: ["transactions"] }); qc.invalidateQueries({ queryKey: ["accounts"] }); qc.invalidateQueries({ queryKey: ["dashboard"] }); toast.success("Transaction deleted and balance reversed"); }, onError: (error) => toast.error(friendlyError(error)) });
  const bulk = useMutation({ mutationFn: () => apiPost<{deleted:number}>("/transactions/bulk-delete", { ids: selected }), onSuccess: ({deleted}) => { setSelected([]); qc.invalidateQueries({ queryKey: ["transactions"] }); qc.invalidateQueries({ queryKey: ["accounts"] }); toast.success(`${deleted} transactions removed`); }, onError: (error) => toast.error(friendlyError(error)) });
  const update = (key: string, value: string | boolean) => setForm((current) => ({ ...current, [key]: value }));
  function openEdit(item: Transaction) { setEditingId(item.id); setForm({ type:item.type, amount:String(item.amount), description:item.description, merchant:item.merchant??"", category:item.category, date:item.date, account_id:item.account_id, is_recurring:item.is_recurring, recurring_interval:item.recurring_interval??"MONTHLY" }); setParams({new:"1"}); window.scrollTo({top:0,behavior:"smooth"}); }
  const categories = form.type === "EXPENSE" ? EXPENSE_CATEGORIES : INCOME_CATEGORIES;
  return <div className="space-y-6"><div className="page-title-row"><div><p className="section-kicker">Activity ledger</p><h2 className="page-title" data-testid="transactions-heading">Transactions</h2><p className="page-description">Every change safely adjusts the linked account balance.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>navigate("/scan")} className="border-cyan-400/20 bg-cyan-400/[.04] text-cyan-200" data-testid="scan-receipt-button"><ScanLine size={16}/> Scan receipt</Button><Button onClick={() => setParams(showForm ? {} : {new:"1"})} className="bg-[#00f5a0] text-[#07110c]" data-testid="add-transaction-button">{showForm ? <X size={16}/> : <Plus size={16}/>} {showForm ? "Close" : "Add transaction"}</Button></div></div>
    {showForm && <form className="panel" onSubmit={(e) => {e.preventDefault(); create.mutate();}} data-testid="transaction-create-form"><div className="mb-5 flex items-center justify-between"><div className="flex gap-2">{(["EXPENSE","INCOME"] as const).map((type)=><button type="button" key={type} onClick={()=>{update("type",type); update("category", type === "EXPENSE" ? "Food" : "Salary");}} className={`type-toggle ${form.type===type?"type-toggle-active":""}`} data-testid={`transaction-type-${type.toLowerCase()}`}>{type === "EXPENSE" ? <ArrowUpRight size={16}/> : <ArrowDownLeft size={16}/>} {type}</button>)}</div>{editingId&&<span className="status-dot">Editing transaction</span>}</div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div className="space-y-2"><Label>Amount (₹)</Label><Input type="number" min="1" step="0.01" value={form.amount} onChange={(e)=>update("amount",e.target.value)} required data-testid="transaction-amount-input"/></div><div className="space-y-2"><Label>Description</Label><Input value={form.description} onChange={(e)=>update("description",e.target.value)} placeholder="Dinner with friends" required data-testid="transaction-description-input"/></div><div className="space-y-2"><Label>Merchant</Label><Input value={form.merchant} onChange={(e)=>update("merchant",e.target.value)} placeholder="Optional" data-testid="transaction-merchant-input"/></div><div className="space-y-2"><Label>Date</Label><Input type="date" value={form.date} onChange={(e)=>update("date",e.target.value)} required data-testid="transaction-date-input"/></div><div className="space-y-2"><Label>Category</Label><select className="form-select" value={form.category} onChange={(e)=>update("category",e.target.value)} data-testid="transaction-category-select">{categories.map((category)=><option key={category}>{category}</option>)}</select></div><div className="space-y-2"><Label>Account</Label><select className="form-select" value={form.account_id || accounts.data?.[0]?.id || ""} onChange={(e)=>update("account_id",e.target.value)} required data-testid="transaction-account-select">{accounts.data?.map((a)=><option key={a.id} value={a.id}>{a.name}</option>)}</select></div><label className="flex items-center gap-3 self-end pb-3 text-sm text-slate-300"><Checkbox checked={form.is_recurring} onCheckedChange={(checked)=>update("is_recurring",checked===true)} data-testid="transaction-recurring-checkbox"/>Recurring monthly</label><Button type="submit" disabled={create.isPending || !accounts.data?.length} className="self-end" data-testid="transaction-save-button">{create.isPending?"Saving…":editingId?"Update transaction":"Save transaction"}</Button></div></form>}
    <div className="panel !p-3 sm:!p-4"><div className="grid gap-3 sm:grid-cols-[1fr_160px_160px_auto]"><div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-600" size={16}/><Input className="pl-9" value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Search description or merchant" data-testid="transaction-search-input"/></div><select className="form-select" value={filter} onChange={(e)=>setFilter(e.target.value)} data-testid="transaction-type-filter"><option value="">All activity</option><option value="EXPENSE">Expenses</option><option value="INCOME">Income</option></select><select className="form-select" value={sort} onChange={(e)=>setSort(e.target.value)} data-testid="transaction-sort-select"><option value="newest">Newest</option><option value="oldest">Oldest</option><option value="highest">Highest value</option></select>{selected.length>0&&<Button variant="destructive" onClick={()=>bulk.mutate()} data-testid="transactions-bulk-delete-button"><Trash2 size={15}/> Delete {selected.length}</Button>}</div></div>
    <div className="panel overflow-hidden !p-0" data-testid="transactions-table"><div className="hidden grid-cols-[40px_1.3fr_.7fr_.7fr_.6fr_76px] gap-4 border-b border-white/8 px-5 py-3 text-[10px] uppercase tracking-[.15em] text-slate-600 md:grid"><span></span><span>Transaction</span><span>Category</span><span>Date</span><span className="text-right">Amount</span><span></span></div>{list.isLoading&&<div className="p-8 text-center text-sm text-slate-500">Loading your financial activity…</div>}{list.data?.items.map((item)=><div key={item.id} className="grid gap-3 border-b border-white/6 px-4 py-4 last:border-0 md:grid-cols-[40px_1.3fr_.7fr_.7fr_.6fr_76px] md:items-center md:gap-4 md:px-5" data-testid={`transaction-row-${item.id}`}><Checkbox checked={selected.includes(item.id)} onCheckedChange={(checked)=>setSelected((current)=>checked?[...current,item.id]:current.filter((id)=>id!==item.id))} data-testid={`transaction-select-${item.id}`}/><div><p className="text-sm font-medium">{item.description}</p><p className="mt-1 text-xs text-slate-500">{item.merchant||"No merchant"}</p></div><span className="w-fit rounded-full bg-white/[.05] px-2.5 py-1 text-xs text-slate-400">{item.category}</span><span className="text-xs text-slate-500">{item.date}</span><span className={`money-value text-right text-sm ${item.type==="INCOME"?"text-[#00f5a0]":"text-slate-100"}`}>{item.type==="EXPENSE"?"−":"+"}{formatINR(item.amount)}</span><div className="flex"><button onClick={()=>openEdit(item)} className="icon-button" data-testid={`transaction-edit-${item.id}`} aria-label={`Edit ${item.description}`}><Pencil size={14}/></button><button onClick={()=>{if(confirm("Delete and reverse this transaction?"))remove.mutate(item.id);}} className="icon-button" data-testid={`transaction-delete-${item.id}`} aria-label={`Delete ${item.description}`}><Trash2 size={15}/></button></div></div>)}{list.data?.items.length===0&&<div className="empty-state !border-0" data-testid="transactions-empty-state"><Search/><p>No transactions match this view.</p></div>}</div>
    {list.data&&<p className="text-xs text-slate-600" data-testid="transactions-count">Showing {list.data.items.length} of {list.data.total} transactions</p>}
  </div>;
}